{% set name = "pyIEM" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 149da1f946665dad76bbefdc2e5dc6701212b337ce583a3a5b58b7d7b4730638

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
    - setuptools_scm

  run:
    - python >=3.6
    - affine
    - backports.zoneinfo
    - cartopy >=0.18
    - descartes
    - geopandas
    - jinja2
    - matplotlib-base
    - metpy
    - netCDF4
    - numpy
    - pandas
    - pillow
    - pyarrow
    - pydantic
    - pyproj
    - psycopg2
    - rasterio
    - requests
    - scipy
    - shapely
    - xarray

test:
  imports:
    - pyiem

about:
  home: https://github.com/akrherz/pyIEM
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A general library supporting NWS Products and the IEM Project.
  description: |
    pyIEM contains a wide collection of codes relevant for working with
    US National Weather Service data and code that supports the Iowa
    Environmental Mesonet project at Iowa State University.
  dev_url: https://github.com/akrherz/pyIEM

extra:
  recipe-maintainers:
    - akrherz
