{% set name = "pyIEM" %}
{% set version = "1.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7b9026d03586ae09ff75415b439c15136aa9335e4f5b669c4fbe587cce7eef5e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
    - setuptools_scm

  run:
    - python >=3.8
    - affine
    - defusedxml
    - geopandas
    - jinja2
    - matplotlib-base
    - metar
    - metpy
    - netCDF4
    - nh3
    - numpy
    - pandas
    - paste
    - pillow
    - pyarrow
    - pydantic
    - pymemcache
    - pyproj
    - psycopg
    - rasterio
    - rasterstats
    - requests
    - scipy
    - shapely
    - sqlalchemy
    - twython
    - xarray

test:
  imports:
    - pyiem

about:
  home: https://github.com/akrherz/pyIEM
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A general library supporting NWS Products and the IEM Project.
  description: |
    pyIEM contains a wide collection of codes relevant for working with
    US National Weather Service data and code that supports the Iowa
    Environmental Mesonet project at Iowa State University.
  dev_url: https://github.com/akrherz/pyIEM

extra:
  recipe-maintainers:
    - akrherz
