{% set name = "pyIEM" %}
{% set version = "1.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: baf2dcbfc0982c5abf78b6fc4935d4132d621c038536be2c03cffb0aa06ad74b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
    - setuptools_scm

  run:
    - python >=3.8
    - affine
    - geopandas
    - google-api-python-client
    - jinja2
    - matplotlib-base
    - metar
    - metpy
    - netCDF4
    - numpy
    - pandas
    - pillow
    - pyarrow
    - pydantic
    - pyproj
    - psycopg2
    - rasterio
    - rasterstats
    - requests
    - scipy
    - shapely
    - sqlalchemy
    # Sneeky way to get backports.zoneinfo
    - tzlocal
    - xarray

test:
  imports:
    - pyiem

about:
  home: https://github.com/akrherz/pyIEM
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A general library supporting NWS Products and the IEM Project.
  description: |
    pyIEM contains a wide collection of codes relevant for working with
    US National Weather Service data and code that supports the Iowa
    Environmental Mesonet project at Iowa State University.
  dev_url: https://github.com/akrherz/pyIEM

extra:
  recipe-maintainers:
    - akrherz
